"""Add login lock and reset fields

Revision ID: 463c06fe1100
Revises: 
Create Date: 2025-10-15 12:48:24.511379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463c06fe1100'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token_expiry')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('is_locked')
        batch_op.drop_column('failed_attempts')

    # ### end Alembic commands ###
