"""Add case status, handler, and contact message model

Revision ID: 5b0b6bf7cf32
Revises: 3a5c1603f9ea
Create Date: 2025-09-30 08:45:07.704385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0b6bf7cf32'
down_revision = '3a5c1603f9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('handled_by', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('handled_by')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
