"""Add next_hearing_date to case

Revision ID: 5cce7fe4ce0a
Revises: 463c06fe1100
Create Date: 2025-10-15 16:15:07.959656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cce7fe4ce0a'
down_revision = '463c06fe1100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casess', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_hearing_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casess', schema=None) as batch_op:
        batch_op.drop_column('next_hearing_date')

    # ### end Alembic commands ###
