"""Add reply fields to ContactMessage and admin role to User

Revision ID: 66df8dccc689
Revises: f2f0489984a3
Create Date: 2025-10-08 12:46:56.968895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66df8dccc689'
down_revision = 'f2f0489984a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cases')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=50), nullable=True))

    op.create_table('cases',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_number', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('case_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('parties', mysql.TEXT(), nullable=False),
    sa.Column('date_filed', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('handled_by', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('date_closed', mysql.DATETIME(), nullable=True),
    sa.Column('date_paused', mysql.DATETIME(), nullable=True),
    sa.Column('date_resumed', mysql.DATETIME(), nullable=True),
    sa.Column('department', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('descriptions', mysql.TEXT(), nullable=True),
    sa.Column('records', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
