"""Add status history fields to case

Revision ID: cc037068950c
Revises: 5b0b6bf7cf32
Create Date: 2025-09-30 10:59:00.450620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc037068950c'
down_revision = '5b0b6bf7cf32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_closed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_paused', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_resumed', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('date_resumed')
        batch_op.drop_column('date_paused')
        batch_op.drop_column('date_closed')

    # ### end Alembic commands ###
