"""Add hearing_mode, court_link and link_title to case

Revision ID: dd9bfdf053b0
Revises: 8c2291c596b1
Create Date: 2025-10-21 13:42:01.054461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9bfdf053b0'
down_revision = '8c2291c596b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casess', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hearing_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('court_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('link_title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casess', schema=None) as batch_op:
        batch_op.drop_column('link_title')
        batch_op.drop_column('court_link')
        batch_op.drop_column('hearing_mode')

    # ### end Alembic commands ###
