"""Add role to User and reply fields to ContactMessage

Revision ID: f2f0489984a3
Revises: 3970403ad2c7
Create Date: 2025-10-07 09:25:44.403543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2f0489984a3'
down_revision = '3970403ad2c7'
branch_labels = None
depends_on = None


def upgrade():
    # op.drop_table('cases')  # Already dropped manually

    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('replied_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('replied_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['replied_by'], ['id'])

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('document_case_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'casess', ['case_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('document_case_id_fkey'), 'cases', ['case_id'], ['id'])

    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('replied_by')
        batch_op.drop_column('replied_at')
        batch_op.drop_column('reply')

    #op.create_table('cases',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_number', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('case_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('parties', mysql.TEXT(), nullable=False),
    sa.Column('date_filed', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('handled_by', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('date_closed', mysql.DATETIME(), nullable=True),
    sa.Column('date_paused', mysql.DATETIME(), nullable=True),
    sa.Column('date_resumed', mysql.DATETIME(), nullable=True),
    sa.Column('department', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('descriptions', mysql.TEXT(), nullable=True),
    sa.Column('records', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    
    # ### end Alembic commands ###
